name: ARGCP
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10.8
  - numpy=1.25.2
  - networkx=2.8.4
  - biopython=1.81
  - pysam=0.21.0
  - seaborn=0.12.2
  - matplotlib-base=3.7.1
  - pyfastg=0.1.0
  - prokka=1.14.6
  - prodigal=2.6.3
  - mmseqs2=15.6f452
  - diamond=2.1.6
  - bwa=0.7.17
  - samtools=1.17
  - spades=3.15.5
  - nextflow
  - pip=23.0.1
  - pip:
      - clinker==0.0.31
      - pandas==2.2.2
