name: argcp
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - biopython
  - networkx
  - pysam
  - scipy
  - scikit-learn
  - pyfastg
  - blast
  - diamond
  - prokka
  - prodigal
  - spades
  - sra-tools
  - clinker
